# Generated by Django 3.0.2 on 2020-01-16 18:40

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200115_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
